### ISSUE TITLE
Trying to run tightcnc but getting enableServer error

### ISSUE THREAD

**Issue by nccwarp9** [crispy1989/tightcnc#6]
tightcnc-server
{ XError: enableServer config flag now found.  Ensure configuration is correct - check the documentation.
    at new XError (/usr/local/lib/node_modules/tightcnc/node_modules/xerror/xerror.js:20:37)
    at new TightCNCServer (/usr/local/lib/node_modules/tightcnc/src/server/tightcnc-server.js:40:10)
    at startServer (/usr/local/lib/node_modules/tightcnc/src/server/server.js:17:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tightcnc/src/server/server.js:73:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
  code: 'invalid_argument',
  message: 'enableServer config flag now found.  Ensure configuration is correct - check the documentation.',
  data: undefined,
  privateData: undefined,
  cause: undefined,
  name: 'XError' }
XError: enableServer config flag now found.  Ensure configuration is correct - check the documentation.
    at new XError (/usr/local/lib/node_modules/tightcnc/node_modules/xerror/xerror.js:20:37)
    at new TightCNCServer (/usr/local/lib/node_modules/tightcnc/src/server/tightcnc-server.js:40:10)
    at startServer (/usr/local/lib/node_modules/tightcnc/src/server/server.js:17:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tightcnc/src/server/server.js:73:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
ncc@ncc-cnc:~$

**Comment by nccwarp9** [comment]
config file was not written due to permissions... fixed
